/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.Graphics;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.ThongTin_BangTheoDoi;
import model.ThongTin_DeTai;
import model.ThongTin_GiangVien;

/**
 *
 * @author Kien_BKHN
 */
public class frmSuaThongTinDeTai extends javax.swing.JFrame {

    String LINK_IMAGE = "12345.JPG";

    panelHienThiChiTietDeTai pnHienThi;

    ThongTin_DeTai objDeTai = new ThongTin_DeTai();

    public frmSuaThongTinDeTai() {
        initComponents();
    }

    frmSuaThongTinDeTai(panelHienThiChiTietDeTai pnHienThi,ThongTin_DeTai objDeTai) {
        initComponents();

        this.pnHienThi = pnHienThi;

        this.objDeTai = objDeTai;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){

            ImageIcon icon = new ImageIcon(LINK_IMAGE);
            public void paintComponent(Graphics g) {
                Dimension d = this.getSize();
                g.drawImage(icon.getImage(),0,0,d.width,d.height,null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        txtMaDeTai = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenDeTai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLoaiDeTai = new javax.swing.JTextField();
        txtCapDeTai = new javax.swing.JTextField();
        txtDonViChuTri = new javax.swing.JTextField();
        txtDonViThucHien = new javax.swing.JTextField();
        jDateBatDau = new com.toedter.calendar.JDateChooser();
        jDateKetThuc = new com.toedter.calendar.JDateChooser();
        txtKinhPhi = new javax.swing.JTextField();
        txtSoGio = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sửa thông tin"));

        jLabel1.setText("Mã đề tài:");

        jLabel2.setText("Tên đề tài:");

        jLabel3.setText("Loại đề tài:");

        jLabel10.setText("Số giờ quy đổi:");

        jLabel9.setText("Kinh phí thực hiện:");

        jLabel8.setText("Thời gian kết thúc:");

        jLabel7.setText("Thời gian bắt đầu:");

        jLabel5.setText("Đơn vị chủ trì:");

        jLabel4.setText("Cấp đề tài:");

        jLabel6.setText("Đơn vị thực hiện:");

        txtKinhPhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKinhPhiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4))
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTenDeTai, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLoaiDeTai, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCapDeTai, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDonViChuTri, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDonViThucHien, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKinhPhi, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSoGio, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaDeTai)
                    .addComponent(jDateBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaDeTai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenDeTai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLoaiDeTai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCapDeTai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDonViChuTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDonViThucHien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jDateBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jDateKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtKinhPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtSoGio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Go.png"))); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOK)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOK))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtMaDeTai.setText(objDeTai.getMaDeTai());
        txtTenDeTai.setText(objDeTai.getTenDeTai());
        txtLoaiDeTai.setText(objDeTai.getLoaiDeTai());
        txtCapDeTai.setText(objDeTai.getCapDeTai());
        txtDonViChuTri.setText(objDeTai.getDonViChuTri());
        txtDonViThucHien.setText(objDeTai.getDonViThucHien());
        jDateBatDau.setDate(Date.valueOf(objDeTai.getThoiGianBatDau()));
        jDateKetThuc.setDate(Date.valueOf(objDeTai.getThoiGianKetThuc()));
        txtKinhPhi.setText(String.valueOf(objDeTai.getKinhPhiThucHien()));
        txtSoGio.setText(String.valueOf(objDeTai.getSoGioQuyDoi()));
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        objDeTai.setMaDeTai(txtMaDeTai.getText().trim());
        objDeTai.setTenDeTai(txtTenDeTai.getText().trim());
        objDeTai.setLoaiDeTai(txtLoaiDeTai.getText().trim());
        objDeTai.setCapDeTai(txtCapDeTai.getText().trim());
        objDeTai.setDonViChuTri(txtDonViChuTri.getText().trim());
        objDeTai.setDonViThucHien(txtDonViThucHien.getText().trim());
        objDeTai.setThoiGianBatDau(dateFormat.format(jDateBatDau.getDate()));
        objDeTai.setThoiGianKetThuc(dateFormat.format(jDateKetThuc.getDate()));
        objDeTai.setKinhPhiThucHien(Double.parseDouble(txtKinhPhi.getText().trim()));
        objDeTai.setSoGioQuyDoi(Double.parseDouble(txtSoGio.getText().trim()));
        
        
        

        try {
            utils.Utils.updateThongTinDeTai(objDeTai);
            JOptionPane.showMessageDialog(null, "Update thành công");
            pnHienThi.hienThiThongTin();
            pnHienThi.hienthiThongTin_ChiTiet(txtMaDeTai.getText());
        } catch (SQLException ex) {
            Logger.getLogger(frmSuaThongTinDeTai.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Xảy ra lỗi update");
        }
        
        

    }//GEN-LAST:event_btnOKActionPerformed

    private void txtKinhPhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKinhPhiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKinhPhiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSuaThongTinDeTai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSuaThongTinDeTai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSuaThongTinDeTai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSuaThongTinDeTai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSuaThongTinDeTai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private com.toedter.calendar.JDateChooser jDateBatDau;
    private com.toedter.calendar.JDateChooser jDateKetThuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCapDeTai;
    private javax.swing.JTextField txtDonViChuTri;
    private javax.swing.JTextField txtDonViThucHien;
    private javax.swing.JTextField txtKinhPhi;
    private javax.swing.JTextField txtLoaiDeTai;
    private javax.swing.JTextField txtMaDeTai;
    private javax.swing.JTextField txtSoGio;
    private javax.swing.JTextField txtTenDeTai;
    // End of variables declaration//GEN-END:variables
}
