/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import model.ThongTin_ChuyenDeDeTai;
import model.ThongTin_DeTai;
import model.ThongTin_GiangVien;
import javax.swing.JFileChooser;
/**
 *
 * @author Admin
 */
public class frmSuaThongTinChuyenDe extends javax.swing.JFrame {

    /**
     * Creates new form frmSuaThongTinChuyenDe
     */
    panelHienThiThongTinChuyenDe pnHienThi;
    ThongTin_ChuyenDeDeTai objChuyenDe = new ThongTin_ChuyenDeDeTai();
    //ThongTin_DeTai objDeTai = new ThongTin_DeTai();
    public frmSuaThongTinChuyenDe() {
        initComponents();
    }
    public frmSuaThongTinChuyenDe(panelHienThiThongTinChuyenDe pnHienThi, ThongTin_ChuyenDeDeTai objChuyenDe){
        initComponents();
        
        this.pnHienThi= pnHienThi;
        
       // this.objDeTai= objDeTai;
        
        this.objChuyenDe= objChuyenDe;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        txtSoHopDong = new javax.swing.JTextField();
        txtBaoCaoChuyenDe = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txtSoThue = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        open1 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        btnHopDong1 = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jRDaThanhToan = new javax.swing.JRadioButton();
        jRChuaThanhToan = new javax.swing.JRadioButton();
        jLabel59 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jDateBatDau = new com.toedter.calendar.JDateChooser();
        txtMaChuyenDe = new javax.swing.JTextField();
        jDateKetThuc = new com.toedter.calendar.JDateChooser();
        txtTenChuyenDe = new javax.swing.JTextField();
        jDateNgayKyHopDong = new com.toedter.calendar.JDateChooser();
        txtMaDeTai = new javax.swing.JTextField();
        jDateNgayThanhLyHopDong = new com.toedter.calendar.JDateChooser();
        txtSoTien = new javax.swing.JTextField();
        txtHopDongThanhLy = new javax.swing.JTextField();
        txtNguoiThucHien = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sửa thông tin"));
        jPanel1.setPreferredSize(new java.awt.Dimension(706, 571));

        jLabel62.setText("Số hợp đồng :");

        jLabel63.setText("Báo cáo chuyên đề :");

        jLabel64.setText("Hợp đồng,thanh lý :");

        jLabel65.setText("Tình trạng thực hiện :");

        jLabel66.setText("Số tiền thuế :");

        txtSoHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoHopDongActionPerformed(evt);
            }
        });

        jLabel43.setText("Mã chuyên đề :");

        jLabel44.setText("Tên chuyên đề:");

        open1.setText("open");
        open1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open1ActionPerformed(evt);
            }
        });

        jLabel45.setText("Mã đề tài :");

        btnHopDong1.setText("open");
        btnHopDong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHopDong1ActionPerformed(evt);
            }
        });

        jLabel57.setText("Thời gian bắt đầu:");

        jLabel58.setText("Thời gian kết thúc:");

        buttonGroup1.add(jRDaThanhToan);
        jRDaThanhToan.setText("Đã thanh toán");

        buttonGroup1.add(jRChuaThanhToan);
        jRChuaThanhToan.setText("Chưa thanh toán");

        jLabel59.setText("Số tiền :");

        jLabel67.setText("Ngày thanh lý hợp đồng:");

        jLabel60.setText("Người thực hiện :");

        txtSoTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoTienActionPerformed(evt);
            }
        });

        jLabel61.setText("Ngày ký hợp đồng :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                        .addComponent(jLabel57)
                        .addComponent(jLabel59)
                        .addComponent(jLabel60)
                        .addComponent(jLabel62)
                        .addComponent(jLabel63)
                        .addComponent(jLabel65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel61, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel67, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel66)
                        .addComponent(jLabel64)
                        .addComponent(jLabel43))
                    .addGap(45, 45, 45)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jDateNgayThanhLyHopDong, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                        .addComponent(jDateNgayKyHopDong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSoThue)
                        .addComponent(txtTenChuyenDe)
                        .addComponent(txtMaDeTai)
                        .addComponent(txtSoTien)
                        .addComponent(txtNguoiThucHien)
                        .addComponent(txtSoHopDong, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jDateKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtHopDongThanhLy)
                                .addComponent(txtBaoCaoChuyenDe, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(open1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(btnHopDong1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jRDaThanhToan)
                            .addGap(34, 34, 34)
                            .addComponent(jRChuaThanhToan))
                        .addComponent(jDateBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMaChuyenDe))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel43)
                        .addComponent(txtMaChuyenDe))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel44)
                        .addComponent(txtTenChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel45)
                        .addComponent(txtMaDeTai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel57)
                        .addComponent(jDateBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel58)
                        .addComponent(jDateKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel59)
                        .addComponent(txtSoTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel60)
                        .addComponent(txtNguoiThucHien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel61)
                        .addComponent(jDateNgayKyHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel67)
                        .addComponent(jDateNgayThanhLyHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel62)
                        .addComponent(txtSoHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel63)
                        .addComponent(open1)
                        .addComponent(txtBaoCaoChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel64)
                        .addComponent(btnHopDong1)
                        .addComponent(txtHopDongThanhLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRDaThanhToan)
                            .addComponent(jRChuaThanhToan)))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel66)
                        .addComponent(txtSoThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        txtMaChuyenDe.setText(objChuyenDe.getMaChuyenDe());
        
        txtMaChuyenDe.setEnabled(false);
        
        txtTenChuyenDe.setText(objChuyenDe.getTenChuyenDe());
        
        txtMaDeTai.setText(objChuyenDe.getMaDeTai());
        
        txtSoTien.setText(String.valueOf(objChuyenDe.getSoTien()));
        
        txtNguoiThucHien.setText(objChuyenDe.getNguoiThucHien());
        
        txtSoHopDong.setText(objChuyenDe.getSoHopDong());
        
        txtSoThue.setText(String.valueOf(objChuyenDe.getSoTienThue()));
        
        txtBaoCaoChuyenDe.setText(objChuyenDe.getBaoCaoChuyenDe());
        
        txtHopDongThanhLy.setText(objChuyenDe.getHopDongVaThanhLy());
        
        if (objChuyenDe.getTinhTrangThucHien().equals("Đã thanh toán"))
            jRDaThanhToan.setSelected(true);
        else jRChuaThanhToan.setSelected(true);
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SimpleDateFormat dateFormat= new SimpleDateFormat("yyyy/MM/dd");
      
        objChuyenDe.setTenChuyenDe(txtTenChuyenDe.getText().trim());
        
        objChuyenDe.setMaDeTai(txtMaDeTai.getText().trim());
        
        objChuyenDe.setThoiGianBatDau(dateFormat.format(jDateBatDau.getDate()));
        
        objChuyenDe.setThoiGianKetThuc(dateFormat.format(jDateKetThuc.getDate()));
        
        objChuyenDe.setSoTien(Double.parseDouble(txtSoTien.getText().trim()));
        
        objChuyenDe.setNguoiThucHien(txtNguoiThucHien.getText().trim());
        
        objChuyenDe.setNgayKiHopDong(dateFormat.format(jDateNgayKyHopDong.getDate()));
        
        objChuyenDe.setNgayThanhLyHopDong(dateFormat.format(jDateNgayThanhLyHopDong.getDate()));
        
        objChuyenDe.setSoHopDong(txtSoHopDong.getText().trim());
        
        objChuyenDe.setBaoCaoChuyenDe(txtBaoCaoChuyenDe.getText().trim());
        
        objChuyenDe.setHopDongVaThanhLy(txtHopDongThanhLy.getText().trim());
        
        
        
        if (jRChuaThanhToan.isSelected()) {
            objChuyenDe.setTinhTrangThucHien("Chưa thanh toán");
        } else {
            objChuyenDe.setTinhTrangThucHien("Đã thanh toán");
        }

        objChuyenDe.setSoTienThue(Double.parseDouble(txtSoThue.getText().trim()));

        if (objChuyenDe.getMaChuyenDe().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Mã chuyên đề đề tài trống !");

            return;
        } else {

            try {
                utils.Utils.updateThongTinChuyenDe(objChuyenDe);

                JOptionPane.showMessageDialog(null, "Update thành công");
               

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Có lỗi khi update");
                System.out.println(ex.toString());
            }
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtSoHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoHopDongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoHopDongActionPerformed

    private void open1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open1ActionPerformed

        JFileChooser fileChooser = new JFileChooser("D:\\");

            int check = fileChooser.showOpenDialog(fileChooser);

            if (check == JFileChooser.OPEN_DIALOG) {

                File file = fileChooser.getSelectedFile();

                txtBaoCaoChuyenDe.setText(file.getAbsolutePath());

            }

    }//GEN-LAST:event_open1ActionPerformed

    private void btnHopDong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHopDong1ActionPerformed
        JFileChooser fileChooser = new JFileChooser("D:\\");

            int check = fileChooser.showOpenDialog(fileChooser);

            if (check == JFileChooser.OPEN_DIALOG) {

                File file = fileChooser.getSelectedFile();

                txtHopDongThanhLy.setText(file.getAbsolutePath());

            }
    }//GEN-LAST:event_btnHopDong1ActionPerformed

    private void txtSoTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoTienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSuaThongTinChuyenDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSuaThongTinChuyenDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSuaThongTinChuyenDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSuaThongTinChuyenDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSuaThongTinChuyenDe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHopDong1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateBatDau;
    private com.toedter.calendar.JDateChooser jDateKetThuc;
    private com.toedter.calendar.JDateChooser jDateNgayKyHopDong;
    private com.toedter.calendar.JDateChooser jDateNgayThanhLyHopDong;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRChuaThanhToan;
    private javax.swing.JRadioButton jRDaThanhToan;
    private javax.swing.JButton open1;
    private javax.swing.JTextField txtBaoCaoChuyenDe;
    private javax.swing.JTextField txtHopDongThanhLy;
    private javax.swing.JTextField txtMaChuyenDe;
    private javax.swing.JTextField txtMaDeTai;
    private javax.swing.JTextField txtNguoiThucHien;
    private javax.swing.JTextField txtSoHopDong;
    private javax.swing.JTextField txtSoThue;
    private javax.swing.JTextField txtSoTien;
    private javax.swing.JTextField txtTenChuyenDe;
    // End of variables declaration//GEN-END:variables
}
