/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import model.Login;

/**
 *
 * @author Kien_BKHN
 */
public class frmTaiKhoan extends javax.swing.JFrame {

    /**
     * Creates new form frmTaiKhoan
     */
    Login objLogin;
    
    final String LINK_IMAGE_1="image//1234.jpg";
    
    public frmTaiKhoan() {
        
    }
    
    public frmTaiKhoan( Login objLogin) {
        
        initComponents();
        
        this.objLogin= objLogin;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerPanel = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon(LINK_IMAGE_1);
            public void paintComponent(Graphics g) {
                Dimension d = this.getSize();
                g.drawImage(icon.getImage(),0,0,d.width,d.height,null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnHienThiTatCaTaiKhoan = new javax.swing.JMenuItem();
        btnThayDoiTaiKhoanHienTai = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        centerPanel.setLayout(new java.awt.BorderLayout());

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/top_calendar.gif"))); // NOI18N
        jMenu1.setText("Menu");

        btnHienThiTatCaTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/002.png"))); // NOI18N
        btnHienThiTatCaTaiKhoan.setText("Hiển thị tất cả tài khoản");
        btnHienThiTatCaTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiTatCaTaiKhoanActionPerformed(evt);
            }
        });
        jMenu1.add(btnHienThiTatCaTaiKhoan);

        btnThayDoiTaiKhoanHienTai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/renew.png"))); // NOI18N
        btnThayDoiTaiKhoanHienTai.setText("Thay đổi tài khoản hiện tại");
        btnThayDoiTaiKhoanHienTai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThayDoiTaiKhoanHienTaiActionPerformed(evt);
            }
        });
        jMenu1.add(btnThayDoiTaiKhoanHienTai);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Help-16x16.png"))); // NOI18N
        jMenu2.setText("Trợ giúp");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );

        setBounds(0, 0, 669, 458);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThayDoiTaiKhoanHienTaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThayDoiTaiKhoanHienTaiActionPerformed
       panelThayDoiTaiKhoanHienTai pnThayDoi= new panelThayDoiTaiKhoanHienTai(objLogin);
       
       centerPanel.removeAll();
       
       centerPanel.add(pnThayDoi, BorderLayout.CENTER);
       
       centerPanel.updateUI();
    }//GEN-LAST:event_btnThayDoiTaiKhoanHienTaiActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setTitle("Quản lý tài khoản người dùng");
        
        if(! objLogin.getIsAdmin()){
            hiddenButton();
        }
        
        
    }//GEN-LAST:event_formWindowOpened

    private void btnHienThiTatCaTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiTatCaTaiKhoanActionPerformed
        panelHienThiTatCaTaiKhoan pnHienThi= new panelHienThiTatCaTaiKhoan();
        
        centerPanel.removeAll();
        
        centerPanel.add(pnHienThi, BorderLayout.CENTER);
        
        centerPanel.updateUI();
        
        
    }//GEN-LAST:event_btnHienThiTatCaTaiKhoanActionPerformed

    public void hiddenButton(){
        
        btnHienThiTatCaTaiKhoan.setEnabled(false);
        
        btnThayDoiTaiKhoanHienTai.setEnabled(true);
        
        
        
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTaiKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnHienThiTatCaTaiKhoan;
    private javax.swing.JMenuItem btnThayDoiTaiKhoanHienTai;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
