/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import java.awt.Dimension;
import java.awt.Graphics;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;
import model.ThongTin_BangTheoDoi;
import model.ThongTin_CacChiPhiKhac;
import model.ThongTin_DeTai;
import model.ThongTin_GiangVien;
import model.ThongTin_ChuyenDeDeTai;

/**
 *
 * @author Kien_BKHN
 */
public class panelThemMoiThongTin extends javax.swing.JPanel {

    final String LINK_IMAGE = "image//12345.jpg";

    public panelThemMoiThongTin() {
        initComponents();
        txtBaoCaoChuyenDe.setEnabled(false);
        txtHopDongThanhLy.setEnabled(false);

    }

    private void clearFormChuyenDe() {
        txtMaChuyenDe.setText(null);
        txtTenChuyenDe.setText(null);
        txtMaDeTai_3.setText(null);
        jDateBatDau1.setDate(null);
        jDateKetThuc1.setDate(null);
        txtSoTien.setText(null);
        txtNguoiThucHien.setText(null);
        jDateNgayKyHopDong.setDate(null);
        jDateNgayThanhLyHopDong.setDate(null);
        txtSoHopDong.setText(null);
        txtBaoCaoChuyenDe.setText(null);
        txtHopDongThanhLy.setText(null);
        jRDaThanhToan.setSelected(true);
        txtSoThue.setText(null);
    }

    private void clearFormGiangVien() {
        txtMaGiaoVien.setText(null);
        txtMaDeTai_2.setText(null);
        txtHoTenGV.setText(null);
        txtChucDanh.setText(null);
        txtDienThoai.setText(null);
        txtEmail.setText(null);
        txtDiaChi.setText(null);
        txtBoMon.setText(null);
        txtChiBo.setText(null);
        txtGhiChu.setText(null);
        jDateNgaySinh.setDate(null);
    }

    private void clearFormTheoDoi() {
        tfMaTheoDoi.setText(null);
        tfMaDeTai.setText(null);
        tfLyDo.setText(null);
        tfSoTien.setText(null);
        jDateNgayThucHien.setDate(null);
        tfNguoiThucHien.setText(null);
        tfGhiChu.setText(null);
    }

    private void clearFormChiPhiKhac() {
        tfMaChiKhac.setText(null);
        tfMaDeTai2.setText(null);
        tfLyDo2.setText(null);
        tfSoTien2.setText(null);
        jDateThoiGianBatDau.setDate(null);
        jDateThoiGianKetThuc.setDate(null);
        tfNguoiThucHien2.setText(null);
        jDateThoiGianChi.setDate(null);
        tfGhiChu2.setText(null);
        tfTinhTrangChi.setText(null);
    }

    private void clearFormDeTai() {
        txtMaDeTai.setText(null);
        txtTenDeTai.setText(null);
        txtLoaiDeTai.setText(null);
        txtCapDeTai.setText(null);
        txtDonViChuTri.setText(null);
        txtDonViThucHien.setText(null);
        jDateBatDau.setDate(null);
        jDateKetThuc.setDate(null);
        txtKinhPhi.setText(null);
        txtSoGio.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPaneChuyenDe = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon(LINK_IMAGE);
            public void paintComponent(Graphics g) {
                Dimension d = this.getSize();
                g.drawImage(icon.getImage(),0,0,d.width,d.height,null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnThem_2 = new javax.swing.JButton();
        btnThemTuFile_2 = new javax.swing.JButton();
        txtMaGiaoVien = new javax.swing.JTextField();
        txtMaDeTai_2 = new javax.swing.JTextField();
        txtHoTenGV = new javax.swing.JTextField();
        txtChucDanh = new javax.swing.JTextField();
        txtDienThoai = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtBoMon = new javax.swing.JTextField();
        txtGhiChu = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtChiBo = new javax.swing.JTextField();
        jDateNgaySinh = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon(LINK_IMAGE);
            public void paintComponent(Graphics g) {
                Dimension d = this.getSize();
                g.drawImage(icon.getImage(),0,0,d.width,d.height,null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tfMaTheoDoi = new javax.swing.JTextField();
        tfMaDeTai = new javax.swing.JTextField();
        tfLyDo = new javax.swing.JTextField();
        tfSoTien = new javax.swing.JTextField();
        tfNguoiThucHien = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tfGhiChu = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDateNgayThucHien = new com.toedter.calendar.JDateChooser();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon(LINK_IMAGE);
            public void paintComponent(Graphics g) {
                Dimension d = this.getSize();
                g.drawImage(icon.getImage(),0,0,d.width,d.height,null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        tfMaChiKhac = new javax.swing.JTextField();
        tfMaDeTai2 = new javax.swing.JTextField();
        tfLyDo2 = new javax.swing.JTextField();
        tfSoTien2 = new javax.swing.JTextField();
        tfNguoiThucHien2 = new javax.swing.JTextField();
        tfGhiChu2 = new javax.swing.JTextField();
        tfTinhTrangChi = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jDateThoiGianBatDau = new com.toedter.calendar.JDateChooser();
        jDateThoiGianKetThuc = new com.toedter.calendar.JDateChooser();
        jDateThoiGianChi = new com.toedter.calendar.JDateChooser();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon(LINK_IMAGE);
            public void paintComponent(Graphics g) {
                Dimension d = this.getSize();
                g.drawImage(icon.getImage(),0,0,d.width,d.height,null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        txtMaChuyenDe = new javax.swing.JTextField();
        txtTenChuyenDe = new javax.swing.JTextField();
        txtMaDeTai_3 = new javax.swing.JTextField();
        txtSoTien = new javax.swing.JTextField();
        txtNguoiThucHien = new javax.swing.JTextField();
        btnThem_4 = new javax.swing.JButton();
        btnThemTuFile_4 = new javax.swing.JButton();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        txtSoHopDong = new javax.swing.JTextField();
        txtBaoCaoChuyenDe = new javax.swing.JTextField();
        txtSoThue = new javax.swing.JTextField();
        open1 = new javax.swing.JButton();
        btnHopDong1 = new javax.swing.JButton();
        jRDaThanhToan = new javax.swing.JRadioButton();
        jRChuaThanhToan = new javax.swing.JRadioButton();
        jLabel67 = new javax.swing.JLabel();
        jDateBatDau1 = new com.toedter.calendar.JDateChooser();
        jDateKetThuc1 = new com.toedter.calendar.JDateChooser();
        jDateNgayKyHopDong = new com.toedter.calendar.JDateChooser();
        jDateNgayThanhLyHopDong = new com.toedter.calendar.JDateChooser();
        txtHopDongThanhLy = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon(LINK_IMAGE);
            public void paintComponent(Graphics g) {
                Dimension d = this.getSize();
                g.drawImage(icon.getImage(),0,0,d.width,d.height,null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaDeTai = new javax.swing.JTextField();
        txtTenDeTai = new javax.swing.JTextField();
        txtLoaiDeTai = new javax.swing.JTextField();
        txtCapDeTai = new javax.swing.JTextField();
        txtDonViChuTri = new javax.swing.JTextField();
        txtDonViThucHien = new javax.swing.JTextField();
        txtKinhPhi = new javax.swing.JTextField();
        txtSoGio = new javax.swing.JTextField();
        btnThem_1 = new javax.swing.JButton();
        btnThemTuFile_1 = new javax.swing.JButton();
        jDateBatDau = new com.toedter.calendar.JDateChooser();
        jDateKetThuc = new com.toedter.calendar.JDateChooser();
        jLabel40 = new javax.swing.JLabel();
        txtLink = new javax.swing.JTextField();
        btnOpen = new javax.swing.JButton();

        jTabbedPaneChuyenDe.setToolTipText("");

        jLabel12.setText("Mã giáo viên:");

        jLabel13.setText("Mã đề tài:");

        jLabel14.setText("Họ tên giáo viên:");

        jLabel15.setText("Chức danh:");

        jLabel16.setText("Điện thoại:");

        jLabel17.setText("Email:");

        jLabel18.setText("Địa chỉ:");

        jLabel19.setText("Bộ môn:");

        jLabel20.setText("Ghi chú:");

        jLabel21.setText("Ngày sinh:");

        btnThem_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/103.png"))); // NOI18N
        btnThem_2.setText("Thêm");
        btnThem_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_2ActionPerformed(evt);
            }
        });

        btnThemTuFile_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/AddTableHS.png"))); // NOI18N
        btnThemTuFile_2.setText("Thêm từ file");
        btnThemTuFile_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTuFile_2ActionPerformed(evt);
            }
        });

        txtMaGiaoVien.setText("Bắt buộc nhập");

        txtMaDeTai_2.setText("Bắt buộc nhập");

        jLabel22.setText("Chi bộ:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThemTuFile_2)
                .addGap(18, 18, 18)
                .addComponent(btnThem_2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                            .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtChiBo, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtBoMon, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addComponent(jLabel21)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18))
                            .addGap(32, 32, 32)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDiaChi)
                                .addComponent(txtEmail)
                                .addComponent(txtDienThoai)
                                .addComponent(txtChucDanh)
                                .addComponent(txtMaGiaoVien)
                                .addComponent(txtMaDeTai_2)
                                .addComponent(txtHoTenGV)
                                .addComponent(jDateNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtMaGiaoVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel14)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtChucDanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtBoMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txtChiBo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtMaDeTai_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtHoTenGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jDateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemTuFile_2)
                            .addComponent(btnThem_2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(39, 39, 39))))
        );

        jScrollPane1.setViewportView(jPanel2);

        jTabbedPaneChuyenDe.addTab("Thông tin giảng viên", jScrollPane1);

        jLabel23.setText("Mã theo dõi:");

        jLabel24.setText("Mã đề tài:");

        jLabel25.setText("Lý do:");
        jLabel25.setToolTipText("");

        jLabel26.setText("Số tiền:");

        jLabel27.setText("Ngày thực hiện:");

        jLabel28.setText("Người thực hiện:");

        jLabel29.setText("Ghi chú:");

        tfMaTheoDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaTheoDoiActionPerformed(evt);
            }
        });

        tfGhiChu.setColumns(20);
        tfGhiChu.setRows(5);
        jScrollPane4.setViewportView(tfGhiChu);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/AddTableHS.png"))); // NOI18N
        jButton1.setText("Thêm từ file");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/103.png"))); // NOI18N
        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNguoiThucHien)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jDateNgayThucHien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfMaTheoDoi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMaDeTai, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfLyDo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfSoTien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(179, 179, 179))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(204, 204, 204))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tfMaTheoDoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tfMaDeTai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tfLyDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(tfSoTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jDateNgayThucHien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(tfNguoiThucHien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel3);

        jTabbedPaneChuyenDe.addTab("Thông tin theo dõi", jScrollPane3);

        jLabel30.setText("Mã chi khác:");

        jLabel31.setText("Mã đề tài:");

        jLabel32.setText("Lý do:");

        jLabel33.setText("Số tiền:");

        jLabel34.setText("Thời gian bắt đầu:");

        jLabel35.setText("Thời gian kết thúc:");

        jLabel36.setText("Người thực hiện:");

        jLabel37.setText("Thời gian chi:");

        jLabel38.setText("Ghi chú:");

        jLabel39.setText("Tình trạng chi:");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/AddTableHS.png"))); // NOI18N
        jButton3.setText("Thêm từ file");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/103.png"))); // NOI18N
        jButton4.setText("Thêm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfMaChiKhac, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addComponent(tfMaDeTai2)
                    .addComponent(tfLyDo2)
                    .addComponent(tfSoTien2)
                    .addComponent(tfNguoiThucHien2)
                    .addComponent(tfGhiChu2)
                    .addComponent(tfTinhTrangChi)
                    .addComponent(jDateThoiGianBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateThoiGianKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateThoiGianChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(410, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(125, 125, 125))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(tfMaChiKhac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(tfMaDeTai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(tfLyDo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(tfSoTien2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jDateThoiGianBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jDateThoiGianKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(tfNguoiThucHien2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(jDateThoiGianChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(tfGhiChu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(tfTinhTrangChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(40, 40, 40))
        );

        jScrollPane5.setViewportView(jPanel4);

        jTabbedPaneChuyenDe.addTab("Thông tin chi phí khác", jScrollPane5);

        jPanel6.setAutoscrolls(true);

        jLabel43.setText("Mã chuyên đề :");

        jLabel44.setText("Tên chuyên đề:");

        jLabel45.setText("Mã đề tài :");

        jLabel57.setText("Thời gian bắt đầu:");

        jLabel58.setText("Thời gian kết thúc:");

        jLabel59.setText("Số tiền :");

        jLabel60.setText("Người thực hiện :");

        txtSoTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoTienActionPerformed(evt);
            }
        });

        btnThem_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/103.png"))); // NOI18N
        btnThem_4.setText("Thêm");
        btnThem_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_4ActionPerformed(evt);
            }
        });

        btnThemTuFile_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/AddTableHS.png"))); // NOI18N
        btnThemTuFile_4.setText("Thêm vào từ file");
        btnThemTuFile_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTuFile_4ActionPerformed(evt);
            }
        });

        jLabel61.setText("Ngày ký hợp đồng :");

        jLabel62.setText("Số hợp đồng :");

        jLabel63.setText("Báo cáo chuyên đề :");

        jLabel64.setText("Hợp đồng,thanh lý :");

        jLabel65.setText("Tình trạng thực hiện :");

        jLabel66.setText("Số tiền thuế :");

        txtSoHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoHopDongActionPerformed(evt);
            }
        });

        open1.setText("open");
        open1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open1ActionPerformed(evt);
            }
        });

        btnHopDong1.setText("open");
        btnHopDong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHopDong1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRDaThanhToan);
        jRDaThanhToan.setText("Đã thanh toán");

        buttonGroup1.add(jRChuaThanhToan);
        jRChuaThanhToan.setText("Chưa thanh toán");

        jLabel67.setText("Ngày thanh lý hợp đồng:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel43)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                    .addComponent(jLabel57)
                    .addComponent(jLabel59)
                    .addComponent(jLabel60)
                    .addComponent(jLabel62)
                    .addComponent(jLabel63)
                    .addComponent(jLabel65)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel61, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel67, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel66)
                    .addComponent(jLabel64))
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateBatDau1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnThemTuFile_4)
                                .addGap(42, 42, 42)
                                .addComponent(btnThem_4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jDateNgayThanhLyHopDong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                                    .addComponent(jDateNgayKyHopDong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSoThue, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenChuyenDe, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaDeTai_3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoTien, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNguoiThucHien, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaChuyenDe)
                                    .addComponent(txtSoHopDong)
                                    .addComponent(jDateKetThuc1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtHopDongThanhLy)
                                            .addComponent(txtBaoCaoChuyenDe, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(open1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(btnHopDong1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(75, 75, 75))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jRDaThanhToan)
                        .addGap(34, 34, 34)
                        .addComponent(jRChuaThanhToan)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(txtMaChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(txtTenChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(txtMaDeTai_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel57)
                    .addComponent(jDateBatDau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel58)
                    .addComponent(jDateKetThuc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(txtSoTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60)
                    .addComponent(txtNguoiThucHien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel61)
                    .addComponent(jDateNgayKyHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel67)
                    .addComponent(jDateNgayThanhLyHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(txtSoHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63)
                    .addComponent(open1)
                    .addComponent(txtBaoCaoChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64)
                    .addComponent(btnHopDong1)
                    .addComponent(txtHopDongThanhLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel65)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRDaThanhToan)
                        .addComponent(jRChuaThanhToan)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(txtSoThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemTuFile_4)
                    .addComponent(btnThem_4))
                .addGap(19, 19, 19))
        );

        jScrollPane6.setViewportView(jPanel6);

        jTabbedPaneChuyenDe.addTab("Chuyên đề đề tài", jScrollPane6);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setAutoscrolls(true);

        jLabel1.setText("Mã đề tài:");

        jLabel2.setText("Tên đề tài:");

        jLabel3.setText("Loại đề tài:");

        jLabel4.setText("Cấp đề tài:");

        jLabel5.setText("Đơn vị chủ trì:");

        jLabel6.setText("Đơn vị thực hiện:");

        jLabel7.setText("Thời gian bắt đầu:");

        jLabel8.setText("Thời gian kết thúc:");

        jLabel9.setText("Kinh phí thực hiện:");

        jLabel10.setText("Số giờ quy đổi:");

        txtKinhPhi.setText("99999999999999");
        txtKinhPhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKinhPhiActionPerformed(evt);
            }
        });

        txtSoGio.setText("99999999999999");

        btnThem_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/103.png"))); // NOI18N
        btnThem_1.setText("Thêm");
        btnThem_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_1ActionPerformed(evt);
            }
        });

        btnThemTuFile_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/AddTableHS.png"))); // NOI18N
        btnThemTuFile_1.setText("Thêm vào từ file");
        btnThemTuFile_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTuFile_1ActionPerformed(evt);
            }
        });

        jLabel40.setText("Thuyết minh đề tài:");

        btnOpen.setText("Open");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 441, Short.MAX_VALUE)
                        .addComponent(btnThemTuFile_1)
                        .addGap(18, 18, 18)
                        .addComponent(btnThem_1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel40))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenDeTai)
                            .addComponent(txtLoaiDeTai)
                            .addComponent(txtCapDeTai)
                            .addComponent(txtDonViChuTri)
                            .addComponent(txtDonViThucHien)
                            .addComponent(txtKinhPhi, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                            .addComponent(txtSoGio)
                            .addComponent(txtMaDeTai, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateBatDau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateKetThuc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtLink, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaDeTai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenDeTai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLoaiDeTai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCapDeTai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDonViChuTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDonViThucHien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jDateBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jDateKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtKinhPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtSoGio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(txtLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem_1)
                    .addComponent(btnThemTuFile_1))
                .addGap(28, 28, 28))
        );

        jScrollPane2.setViewportView(jPanel1);

        jTabbedPaneChuyenDe.addTab("Thông tin đề tài", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneChuyenDe)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSoHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoHopDongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoHopDongActionPerformed

    private void btnThemTuFile_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTuFile_4ActionPerformed
        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setCurrentDirectory(new File("D:\\"));

        int i = fileChooser.showOpenDialog(fileChooser);

        if (i == JFileChooser.APPROVE_OPTION) {

            File file = fileChooser.getSelectedFile();

            ThongTin_ChuyenDeDeTai objChuyenDeDeTai;

            try {
                Workbook workBook = Workbook.getWorkbook(file);

                Sheet sheet = workBook.getSheet(0);

                Cell cell;

                for (i = 1; i < sheet.getRows(); i++) {

                    objChuyenDeDeTai = new ThongTin_ChuyenDeDeTai();

                    cell = sheet.getCell(0, i);
                    objChuyenDeDeTai.setMaChuyenDe(cell.getContents());

                    cell = sheet.getCell(1, i);
                    objChuyenDeDeTai.setTenChuyenDe(cell.getContents());

                    cell = sheet.getCell(2, i);
                    objChuyenDeDeTai.setMaDeTai(cell.getContents());

                    cell = sheet.getCell(3, i);
                    objChuyenDeDeTai.setThoiGianBatDau(cell.getContents());

                    cell = sheet.getCell(4, i);
                    objChuyenDeDeTai.setThoiGianKetThuc(cell.getContents());

                    cell = sheet.getCell(5, i);
                    objChuyenDeDeTai.setSoTien(Double.parseDouble(cell.getContents()));

                    cell = sheet.getCell(6, i);
                    objChuyenDeDeTai.setNguoiThucHien(cell.getContents());

                    cell = sheet.getCell(7, i);
                    objChuyenDeDeTai.setNgayKiHopDong(cell.getContents());

                    cell = sheet.getCell(8, i);
                    objChuyenDeDeTai.setNgayThanhLyHopDong(cell.getContents());

                    cell = sheet.getCell(9, i);
                    objChuyenDeDeTai.setSoHopDong(cell.getContents());

                    cell = sheet.getCell(10, i);
                    objChuyenDeDeTai.setBaoCaoChuyenDe(cell.getContents());

                    cell = sheet.getCell(11, i);
                    objChuyenDeDeTai.setHopDongVaThanhLy(cell.getContents());

                    cell = sheet.getCell(12, i);
                    objChuyenDeDeTai.setTinhTrangThucHien(cell.getContents());

                    cell = sheet.getCell(13, i);
                    objChuyenDeDeTai.setSoTienThue(Double.parseDouble(cell.getContents()));

                    utils.Utils.themChuyenDeDeTaiVaoSQL(objChuyenDeDeTai);

                    JOptionPane.showMessageDialog(null, "Thêm mới thành công");

                }

            } catch (BiffException ex) {
                JOptionPane.showMessageDialog(null, "Có lỗi với định dạng file");

            } catch (IOException ex) {
                Logger.getLogger(panelThemMoiThongTin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(panelThemMoiThongTin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnThemTuFile_4ActionPerformed

    private void btnThem_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem_4ActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        ThongTin_ChuyenDeDeTai objChuyenDe = new ThongTin_ChuyenDeDeTai();

        objChuyenDe.setMaChuyenDe(txtMaChuyenDe.getText().trim());

        objChuyenDe.setTenChuyenDe(txtTenChuyenDe.getText().trim());

        objChuyenDe.setMaDeTai(txtMaDeTai_3.getText().trim());

        objChuyenDe.setSoTien(Double.parseDouble(txtSoTien.getText().trim()));

        objChuyenDe.setThoiGianBatDau(dateFormat.format(jDateBatDau1.getDate()));

        objChuyenDe.setThoiGianKetThuc(dateFormat.format(jDateKetThuc1.getDate()));

        objChuyenDe.setNgayKiHopDong(dateFormat.format(jDateNgayKyHopDong.getDate()));

        objChuyenDe.setNgayThanhLyHopDong(dateFormat.format(jDateNgayThanhLyHopDong.getDate()));

        objChuyenDe.setNguoiThucHien(txtNguoiThucHien.getText().trim());

        objChuyenDe.setSoHopDong(txtSoHopDong.getText().trim());

        objChuyenDe.setBaoCaoChuyenDe(renderData(txtBaoCaoChuyenDe.getText().trim()));

        objChuyenDe.setHopDongVaThanhLy(renderData(txtHopDongThanhLy.getText().trim()));

        if (jRChuaThanhToan.isSelected()) {
            objChuyenDe.setTinhTrangThucHien("Chưa thanh toán");
        } else {
            objChuyenDe.setTinhTrangThucHien("Đã thanh toán");
        }

        objChuyenDe.setSoTienThue(Double.parseDouble(txtSoThue.getText().trim()));

        if (objChuyenDe.getMaChuyenDe().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Mã chuyên đề đề tài trống !");

            return;
        } else {

            try {
                utils.Utils.themChuyenDeDeTaiVaoSQL(objChuyenDe);

                JOptionPane.showMessageDialog(null, "Thêm mới thành công");

                clearFormChuyenDe();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Có lỗi khi thêm mới");
                System.out.println(ex.toString());
            }
        }

    }//GEN-LAST:event_btnThem_4ActionPerformed

    private void txtSoTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoTienActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");

        ThongTin_CacChiPhiKhac objChiPhiKhac = new ThongTin_CacChiPhiKhac();

        objChiPhiKhac.setMaChiKhac(tfMaChiKhac.getText().trim());

        objChiPhiKhac.setMaDeTai(tfMaDeTai2.getText().trim());

        objChiPhiKhac.setLiDo(tfLyDo2.getText().trim());

        objChiPhiKhac.setSoTien(Double.parseDouble(tfSoTien2.getText().trim()));

        objChiPhiKhac.setThoiGianBatDau(dateFormat.format(jDateThoiGianBatDau.getDate()));

        objChiPhiKhac.setThoiGianKetThuc(dateFormat.format(jDateThoiGianKetThuc.getDate()));

        objChiPhiKhac.setNguoiThucHien(tfNguoiThucHien2.getText().trim());

        objChiPhiKhac.setThoiGianChi(dateFormat.format(jDateThoiGianChi.getDate()));

        objChiPhiKhac.setGhiChu(tfGhiChu2.getText().trim());

        objChiPhiKhac.setTinhTrang(tfTinhTrangChi.getText().trim());

        if (objChiPhiKhac.getMaChiKhac().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Mã đề tài trống !");

            return;
        } else {

            try {
                utils.Utils.themChiPhiKhacVaoSQL(objChiPhiKhac);

                JOptionPane.showMessageDialog(null, "Thêm mới thành công");
                clearFormChiPhiKhac();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Có lỗi khi thêm mới");
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setCurrentDirectory(new File("D:\\"));
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        int check = fileChooser.showOpenDialog(fileChooser);

        if (check == JFileChooser.APPROVE_OPTION) {

            File file = fileChooser.getSelectedFile();

            ThongTin_CacChiPhiKhac objChiPhiKhac = new ThongTin_CacChiPhiKhac();

            try {
                Workbook workBook = Workbook.getWorkbook(file);

                Sheet sheet = workBook.getSheet(0);

                Cell cell;

                for (int i = 1; i < sheet.getRows(); i++) {

                    cell = sheet.getCell(0, i);
                    objChiPhiKhac.setMaChiKhac(cell.getContents());

                    cell = sheet.getCell(1, i);
                    objChiPhiKhac.setMaDeTai(cell.getContents());

                    cell = sheet.getCell(2, i);
                    objChiPhiKhac.setLiDo(cell.getContents());

                    cell = sheet.getCell(3, i);
                    objChiPhiKhac.setSoTien(Double.parseDouble(cell.getContents()));

                    cell = sheet.getCell(4, i);
                    objChiPhiKhac.setThoiGianBatDau(cell.getContents());

                    cell = sheet.getCell(5, i);
                    objChiPhiKhac.setThoiGianKetThuc(cell.getContents());

                    cell = sheet.getCell(6, i);
                    objChiPhiKhac.setNguoiThucHien(cell.getContents());
                    
                    cell = sheet.getCell(7, i);
                    objChiPhiKhac.setThoiGianChi(cell.getContents());
                    
                    cell = sheet.getCell(8, i);
                    objChiPhiKhac.setGhiChu(cell.getContents());
                    
                    cell = sheet.getCell(9, i);
                    objChiPhiKhac.setTinhTrang(cell.getContents());

                    utils.Utils.themChiPhiKhacVaoSQL(objChiPhiKhac);

                    JOptionPane.showMessageDialog(null, "Thêm mới thành công");
                }

            } catch (BiffException ex) {
                JOptionPane.showMessageDialog(null, "Có lỗi với định dạng file");
            } catch (IOException ex) {
                Logger.getLogger(panelThemMoiThongTin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(panelThemMoiThongTin.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ThongTin_BangTheoDoi objTheoDoi = new ThongTin_BangTheoDoi();

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");

        objTheoDoi.setMaTheoDoi(tfMaTheoDoi.getText().trim());

        objTheoDoi.setMaDeTai(tfMaDeTai.getText().trim());

        objTheoDoi.setLiDo(tfLyDo.getText().trim());

        objTheoDoi.setSoTien(Double.parseDouble(tfSoTien.getText().trim()));

        objTheoDoi.setNgayThucHien(dateFormat.format(jDateNgayThucHien.getDate()));

        objTheoDoi.setNguoiThucHien(tfNguoiThucHien.getText().trim());

        objTheoDoi.setGhiChu(tfGhiChu.getText().trim());

        try {
            utils.Utils.themBangTheoDoiVaoSQL(objTheoDoi);

            JOptionPane.showMessageDialog(null, "Thêm mới thành công");
            clearFormTheoDoi();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Có lỗi khi thêm mới");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setCurrentDirectory(new File("D:\\"));
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        int check = fileChooser.showOpenDialog(fileChooser);

        if (check == JFileChooser.APPROVE_OPTION) {

            File file = fileChooser.getSelectedFile();

            ThongTin_BangTheoDoi objTheoDoi = new ThongTin_BangTheoDoi();

            try {
                Workbook workBook = Workbook.getWorkbook(file);

                Sheet sheet = workBook.getSheet(0);

                Cell cell;

                for (int i = 1; i < sheet.getRows(); i++) {

                    cell = sheet.getCell(0, i);
                    objTheoDoi.setMaTheoDoi(cell.getContents());

                    cell = sheet.getCell(1, i);
                    objTheoDoi.setMaDeTai(cell.getContents());

                    cell = sheet.getCell(2, i);
                    objTheoDoi.setLiDo(cell.getContents());

                    cell = sheet.getCell(3, i);
                    objTheoDoi.setSoTien(Double.parseDouble(cell.getContents()));

                    cell = sheet.getCell(4, i);
                    objTheoDoi.setNgayThucHien(cell.getContents());

                    cell = sheet.getCell(5, i);
                    objTheoDoi.setNguoiThucHien(cell.getContents());

                    cell = sheet.getCell(6, i);
                    objTheoDoi.setGhiChu(cell.getContents());

                    utils.Utils.themBangTheoDoiVaoSQL(objTheoDoi);

                    JOptionPane.showMessageDialog(null, "Thêm mới thành công");
                }

            } catch (BiffException ex) {
                JOptionPane.showMessageDialog(null, "Có lỗi với định dạng file");
            } catch (IOException ex) {
                Logger.getLogger(panelThemMoiThongTin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(panelThemMoiThongTin.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfMaTheoDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaTheoDoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMaTheoDoiActionPerformed

    private void btnThemTuFile_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTuFile_2ActionPerformed
        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setCurrentDirectory(new File("D:\\"));

        int check = fileChooser.showOpenDialog(fileChooser);

        if (check == JFileChooser.APPROVE_OPTION) {

            File file = fileChooser.getSelectedFile();

            ThongTin_GiangVien objGiangVien = new ThongTin_GiangVien();

            try {
                Workbook workBook = Workbook.getWorkbook(file);

                Sheet sheet = workBook.getSheet(0);

                Cell cell;

                for (int i = 1; i < sheet.getRows(); i++) {

                    cell = sheet.getCell(0, i);
                    objGiangVien.setMaGV(cell.getContents());

                    cell = sheet.getCell(1, i);
                    objGiangVien.setMaDeTai(cell.getContents());

                    cell = sheet.getCell(2, i);
                    objGiangVien.setHoTenGV(cell.getContents());

                    cell = sheet.getCell(3, i);
                    objGiangVien.setChucDanh(cell.getContents());

                    cell = sheet.getCell(4, i);
                    objGiangVien.setDienThoai(cell.getContents());

                    cell = sheet.getCell(5, i);
                    objGiangVien.setEmail(cell.getContents());

                    cell = sheet.getCell(6, i);
                    objGiangVien.setDiaChi(cell.getContents());

                    cell = sheet.getCell(7, i);
                    objGiangVien.setBoMon(cell.getContents());

                    cell = sheet.getCell(8, i);
                    objGiangVien.setChiBo(cell.getContents());

                    cell = sheet.getCell(9, i);
                    objGiangVien.setGhiChu(cell.getContents());

                    cell = sheet.getCell(10, i);
                    objGiangVien.setNgaySinh(cell.getContents());

                    utils.Utils.themGiangVienVaoSQL(objGiangVien);
                    
                }
                JOptionPane.showMessageDialog(null, "Thêm mới thành công");

            } catch (BiffException ex) {
                JOptionPane.showMessageDialog(null, "Có lỗi với định dạng file");
            } catch (IOException ex) {
                Logger.getLogger(panelThemMoiThongTin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(panelThemMoiThongTin.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnThemTuFile_2ActionPerformed

    private void btnThem_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem_2ActionPerformed
        ThongTin_GiangVien objGiangVien = new ThongTin_GiangVien();

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");

        objGiangVien.setMaGV(txtMaGiaoVien.getText().trim());

        objGiangVien.setMaDeTai(txtMaDeTai_2.getText().trim());

        objGiangVien.setHoTenGV(txtHoTenGV.getText().trim());

        objGiangVien.setChucDanh(txtChucDanh.getText().trim());

        objGiangVien.setDienThoai(txtDienThoai.getText().trim());

        objGiangVien.setEmail(txtEmail.getText().trim());

        objGiangVien.setDiaChi(txtDiaChi.getText().trim());

        objGiangVien.setBoMon(txtBoMon.getText().trim());

        objGiangVien.setChiBo(txtChiBo.getText().trim());

        objGiangVien.setGhiChu(txtGhiChu.getText().trim());

        objGiangVien.setNgaySinh(dateFormat.format(jDateNgaySinh.getDate()));

        try {
            utils.Utils.themGiangVienVaoSQL(objGiangVien);

            JOptionPane.showMessageDialog(null, "Thêm mới thành công");
            clearFormGiangVien();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Có lỗi khi thêm mới");
        }
    }//GEN-LAST:event_btnThem_2ActionPerformed

    private void btnThemTuFile_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTuFile_1ActionPerformed

        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setCurrentDirectory(new File("D:\\"));

        int i = fileChooser.showOpenDialog(fileChooser);

        if (i == JFileChooser.APPROVE_OPTION) {

            File file = fileChooser.getSelectedFile();

            ThongTin_DeTai objDeTai;

            try {
                Workbook workBook = Workbook.getWorkbook(file);

                Sheet sheet = workBook.getSheet(0);

                Cell cell;

                for (i = 1; i < sheet.getRows(); i++) {

                    objDeTai = new ThongTin_DeTai();

                    cell = sheet.getCell(0, i);
                    objDeTai.setMaDeTai(cell.getContents());

                    cell = sheet.getCell(1, i);
                    objDeTai.setTenDeTai(cell.getContents());

                    cell = sheet.getCell(2, i);
                    objDeTai.setLoaiDeTai(cell.getContents());

                    cell = sheet.getCell(3, i);
                    objDeTai.setCapDeTai(cell.getContents());

                    cell = sheet.getCell(4, i);
                    objDeTai.setDonViChuTri(cell.getContents());

                    cell = sheet.getCell(5, i);
                    objDeTai.setDonViThucHien(cell.getContents());

                    cell = sheet.getCell(6, i);
                    objDeTai.setThoiGianBatDau(cell.getContents());

                    cell = sheet.getCell(7, i);
                    objDeTai.setThoiGianKetThuc(cell.getContents());

                    cell = sheet.getCell(8, i);
                    objDeTai.setKinhPhiThucHien(Double.parseDouble(cell.getContents()));

                    cell = sheet.getCell(9, i);
                    objDeTai.setSoGioQuyDoi(Double.parseDouble(cell.getContents()));

                    utils.Utils.themDeTaiVaoSQL(objDeTai);                    

                }
                JOptionPane.showMessageDialog(null, "Thêm mới thành công");

            } catch (BiffException ex) {
                JOptionPane.showMessageDialog(null, "Có lỗi với định dạng file");

            } catch (IOException ex) {
                Logger.getLogger(panelThemMoiThongTin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(panelThemMoiThongTin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnThemTuFile_1ActionPerformed

    private void btnThem_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem_1ActionPerformed

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");

        ThongTin_DeTai objDeTai = new ThongTin_DeTai();

        objDeTai.setCapDeTai(txtCapDeTai.getText().trim());

        objDeTai.setDonViChuTri(txtDonViChuTri.getText().trim());

        objDeTai.setDonViThucHien(txtDonViThucHien.getText().trim());

        objDeTai.setKinhPhiThucHien(Double.parseDouble(txtKinhPhi.getText().trim()));

        objDeTai.setLoaiDeTai(txtLoaiDeTai.getText().trim());

        objDeTai.setMaDeTai(txtMaDeTai.getText().trim());

        objDeTai.setSoGioQuyDoi(Double.parseDouble(txtSoGio.getText().trim()));

        objDeTai.setTenDeTai(txtTenDeTai.getText().trim());
        
        objDeTai.setThuyetMinhDeTai(renderData(txtLink.getText().trim()));
        
        if (jDateBatDau.getDate() != null && jDateKetThuc.getDate() != null) {
            objDeTai.setThoiGianBatDau(dateFormat.format(jDateBatDau.getDate()));

            objDeTai.setThoiGianKetThuc(dateFormat.format(jDateKetThuc.getDate()));
        }
        else{
            JOptionPane.showMessageDialog(null, "Bạn điền thiếu thông tin");
            return;
        }

        if (objDeTai.getMaDeTai().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Mã đề tài trống !");

            return;
        } else {

            try {
                utils.Utils.themDeTaiVaoSQL(objDeTai);

                JOptionPane.showMessageDialog(null, "Thêm mới thành công");
                clearFormDeTai();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Có lỗi khi thêm mới");
            }
        }
    }//GEN-LAST:event_btnThem_1ActionPerformed

    private void txtKinhPhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKinhPhiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKinhPhiActionPerformed

    private void open1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open1ActionPerformed

        JFileChooser fileChooser = new JFileChooser("D:\\");

        int check = fileChooser.showOpenDialog(fileChooser);

        if (check == JFileChooser.OPEN_DIALOG) {

            File file = fileChooser.getSelectedFile();

            txtBaoCaoChuyenDe.setText(file.getAbsolutePath());

        }


    }//GEN-LAST:event_open1ActionPerformed

    private void btnHopDong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHopDong1ActionPerformed
        JFileChooser fileChooser = new JFileChooser("D:\\");

        int check = fileChooser.showOpenDialog(fileChooser);

        if (check == JFileChooser.OPEN_DIALOG) {

            File file = fileChooser.getSelectedFile();

            txtHopDongThanhLy.setText(file.getAbsolutePath());

        }
    }//GEN-LAST:event_btnHopDong1ActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        JFileChooser fileChooser = new JFileChooser("D:\\");

        int check = fileChooser.showOpenDialog(fileChooser);

        if (check == JFileChooser.OPEN_DIALOG) {

            File file = fileChooser.getSelectedFile();

            txtLink.setText(file.getAbsolutePath());
            
            txtLink.setEnabled(false);

        }
    }//GEN-LAST:event_btnOpenActionPerformed

    public static String renderData(String path) {

        String str = "";

        try {
            FileReader fileReader = new FileReader(new File(path));

            int check_ = fileReader.read();

            while (check_ != -1) {

                str += (char) check_;

                check_ = fileReader.read();
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(panelThemMoiThongTin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(panelThemMoiThongTin.class.getName()).log(Level.SEVERE, null, ex);
        }

        return str;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHopDong1;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnThemTuFile_1;
    private javax.swing.JButton btnThemTuFile_2;
    private javax.swing.JButton btnThemTuFile_4;
    private javax.swing.JButton btnThem_1;
    private javax.swing.JButton btnThem_2;
    private javax.swing.JButton btnThem_4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateBatDau;
    private com.toedter.calendar.JDateChooser jDateBatDau1;
    private com.toedter.calendar.JDateChooser jDateKetThuc;
    private com.toedter.calendar.JDateChooser jDateKetThuc1;
    private com.toedter.calendar.JDateChooser jDateNgayKyHopDong;
    private com.toedter.calendar.JDateChooser jDateNgaySinh;
    private com.toedter.calendar.JDateChooser jDateNgayThanhLyHopDong;
    private com.toedter.calendar.JDateChooser jDateNgayThucHien;
    private com.toedter.calendar.JDateChooser jDateThoiGianBatDau;
    private com.toedter.calendar.JDateChooser jDateThoiGianChi;
    private com.toedter.calendar.JDateChooser jDateThoiGianKetThuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRChuaThanhToan;
    private javax.swing.JRadioButton jRDaThanhToan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPaneChuyenDe;
    private javax.swing.JButton open1;
    private javax.swing.JTextArea tfGhiChu;
    private javax.swing.JTextField tfGhiChu2;
    private javax.swing.JTextField tfLyDo;
    private javax.swing.JTextField tfLyDo2;
    private javax.swing.JTextField tfMaChiKhac;
    private javax.swing.JTextField tfMaDeTai;
    private javax.swing.JTextField tfMaDeTai2;
    private javax.swing.JTextField tfMaTheoDoi;
    private javax.swing.JTextField tfNguoiThucHien;
    private javax.swing.JTextField tfNguoiThucHien2;
    private javax.swing.JTextField tfSoTien;
    private javax.swing.JTextField tfSoTien2;
    private javax.swing.JTextField tfTinhTrangChi;
    private javax.swing.JTextField txtBaoCaoChuyenDe;
    private javax.swing.JTextField txtBoMon;
    private javax.swing.JTextField txtCapDeTai;
    private javax.swing.JTextField txtChiBo;
    private javax.swing.JTextField txtChucDanh;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDienThoai;
    private javax.swing.JTextField txtDonViChuTri;
    private javax.swing.JTextField txtDonViThucHien;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtHoTenGV;
    private javax.swing.JTextField txtHopDongThanhLy;
    private javax.swing.JTextField txtKinhPhi;
    private javax.swing.JTextField txtLink;
    private javax.swing.JTextField txtLoaiDeTai;
    private javax.swing.JTextField txtMaChuyenDe;
    private javax.swing.JTextField txtMaDeTai;
    private javax.swing.JTextField txtMaDeTai_2;
    private javax.swing.JTextField txtMaDeTai_3;
    private javax.swing.JTextField txtMaGiaoVien;
    private javax.swing.JTextField txtNguoiThucHien;
    private javax.swing.JTextField txtSoGio;
    private javax.swing.JTextField txtSoHopDong;
    private javax.swing.JTextField txtSoThue;
    private javax.swing.JTextField txtSoTien;
    private javax.swing.JTextField txtTenChuyenDe;
    private javax.swing.JTextField txtTenDeTai;
    // End of variables declaration//GEN-END:variables
}
